---
collections:
  - name: vultr.cloud
    version: ">=1.12.0"
  - name: linode.cloud
    version: ">=0.44.0"
  - name: community.docker
    version: ">=3.0.0"
  - name: community.general
    version: ">=7.0.0"
  - name: upcloud.cloud
    version: ">=0.9.0"
  - name: google.cloud
    version: ">=1.0.0"
